// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_D8w49jITJx51M7uyTeEyeaV2X3vBMw',
    appId: '1:571143129287:web:94d8b4468e734a0c0796e2',
    messagingSenderId: '571143129287',
    projectId: 'stockmate-936d6',
    authDomain: 'stockmate-936d6.firebaseapp.com',
    storageBucket: 'stockmate-936d6.firebasestorage.app',
    measurementId: 'G-BH2JG1DVBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwNBb8wyt0_tIge9_79zI-53eQ44R62zw',
    appId: '1:571143129287:android:9a3a1ac0a1dfc9880796e2',
    messagingSenderId: '571143129287',
    projectId: 'stockmate-936d6',
    storageBucket: 'stockmate-936d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVkrltheAsixrFL1txlxlqEeJuZ9LP0nw',
    appId: '1:571143129287:ios:ffe52f3246768bc60796e2',
    messagingSenderId: '571143129287',
    projectId: 'stockmate-936d6',
    storageBucket: 'stockmate-936d6.firebasestorage.app',
    iosBundleId: 'com.example.stockMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVkrltheAsixrFL1txlxlqEeJuZ9LP0nw',
    appId: '1:571143129287:ios:ffe52f3246768bc60796e2',
    messagingSenderId: '571143129287',
    projectId: 'stockmate-936d6',
    storageBucket: 'stockmate-936d6.firebasestorage.app',
    iosBundleId: 'com.example.stockMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ_D8w49jITJx51M7uyTeEyeaV2X3vBMw',
    appId: '1:571143129287:web:b02906fb545530920796e2',
    messagingSenderId: '571143129287',
    projectId: 'stockmate-936d6',
    authDomain: 'stockmate-936d6.firebaseapp.com',
    storageBucket: 'stockmate-936d6.firebasestorage.app',
    measurementId: 'G-QLSC0G6HFH',
  );
}
